package client.gui;

import java.util.*;

public class LocalizationManager {
    public static final Locale RU = new Locale("ru", "RU");
    public static final Locale NO = new Locale("no", "NO");
    public static final Locale LT = new Locale("lt", "LT");
    public static final Locale EN_GB = new Locale("en", "GB");

    private final Map<Locale, Map<String, String>> resources = new HashMap<>();
    private Locale currentLocale = RU;

    public LocalizationManager() {
        initializeResources();
    }

    private void initializeResources() {
        // =====================================================================
        // RUSSIAN (ru_RU)
        // =====================================================================
        resources.put(RU, Map.ofEntries(
                Map.entry("app.title", "Vehicle Manager"),
                Map.entry("confirm.exit", "Вы действительно хотите выйти?"),
                Map.entry("auth.login", "Логин"),
                Map.entry("auth.password", "Пароль"),
                Map.entry("auth.register", "Регистрация"),
                Map.entry("auth.login.button", "Войти"),
                Map.entry("auth.register.button", "Зарегистрироваться"),
                Map.entry("auth.login.prompt", "username"),
                Map.entry("auth.password.prompt", "••••••••"),
                Map.entry("auth.error.empty", "Логин и пароль не могут быть пустыми"),
                Map.entry("auth.error.auth", "Неверный логин или пароль"),
                Map.entry("auth.error.register", "Ошибка регистрации"),
                Map.entry("auth.success.login", "✓ Авторизация успешна!"),
                Map.entry("main.user.label", "Пользователь:"),
                Map.entry("main.table.title", "Список объектов"),
                Map.entry("main.visual.title", "Визуализация координат"),
                Map.entry("main.lang.label", "Язык:"),
                Map.entry("main.btn.balance", "Баланс"),
                Map.entry("main.btn.deposit", "Пополнить"),
                Map.entry("main.btn.add", "Добавить"),
                Map.entry("main.btn.remove", "Удалить по ID"),
                Map.entry("main.btn.shuffle", "Перемешать"),
                Map.entry("main.btn.buy", "Купить"),
                Map.entry("main.btn.clear", "Очистить"),
                Map.entry("table.filter", "Фильтры"),
                Map.entry("table.filter.id", "ID"),
                Map.entry("table.filter.name", "Имя"),
                Map.entry("table.filter.owner", "Владелец"),
                Map.entry("table.filter.min_price", "Цена от"),
                Map.entry("table.filter.max_price", "Цена до"),
                Map.entry("table.filter.type", "Тип"),
                Map.entry("table.filter.fuel", "Топливо"),
                Map.entry("table.warning.select_for_delete", "Выберите элемент в таблице для удаления!"),
                Map.entry("table.warning.select_for_buy", "Выберите элемент в таблице для покупки!"),
                Map.entry("table.filter.all_types", "Все типы"),
                Map.entry("table.filter.all_fuels", "Все виды топлива"),
                Map.entry("col.id", "ID"),
                Map.entry("col.name", "Имя"),
                Map.entry("col.coords", "Координаты (X,Y)"),
                Map.entry("col.creation_date", "Дата создания"),
                Map.entry("col.engine_power", "Мощность"),
                Map.entry("col.distance", "Дистанция"),
                Map.entry("col.type", "Тип"),
                Map.entry("col.fuel", "Топливо"),
                Map.entry("col.owner", "Владелец"),
                Map.entry("col.price", "Цена"),
                Map.entry("btn.exit", "Выйти из аккаунта"),
                Map.entry("profile.back", "← Назад в меню"),
                Map.entry("profile.about.label", "Расскажите о себе:"),
                Map.entry("profile.about.prompt", "Введите информацию о себе..."),
                Map.entry("profile.status.online", "Онлайн"),
                Map.entry("dialog.save", "Сохранить"),
                Map.entry("dialog.cancel", "Отмена"),
                Map.entry("dialog.ok", "OK"),
                Map.entry("dialog.confirm", "Подтвердить"),
                Map.entry("dialog.add_vehicle", "Добавить ТС"),
                Map.entry("dialog.edit_vehicle", "Редактировать ТС"),
                Map.entry("dialog.header.add", "Заполните данные нового транспортного средства"),
                Map.entry("dialog.header.edit", "Измените данные ТС"),
                Map.entry("dialog.prompt.name", "Название ТС"),
                Map.entry("dialog.prompt.x", "Координата X"),
                Map.entry("dialog.prompt.y", "Координата Y"),
                Map.entry("dialog.prompt.power", "Мощность двигателя"),
                Map.entry("dialog.prompt.distance", "Пройденная дистанция"),
                Map.entry("dialog.prompt.price", "Цена"),
                Map.entry("dialog.label.name", "Название:"),
                Map.entry("dialog.label.coords", "Координаты (X, Y):"),
                Map.entry("dialog.label.creation_date", "Дата создания:"),
                Map.entry("dialog.label.power", "Мощность двигателя:"),
                Map.entry("dialog.label.distance", "Пройденная дистанция:"),
                Map.entry("dialog.label.type", "Тип:"),
                Map.entry("dialog.label.fuel", "Топливо:"),
                Map.entry("dialog.label.price", "Цена:"),
                Map.entry("dialog.error.invalid_numbers", "Проверьте правильность ввода чисел"),
                Map.entry("dialog.error.empty_collection", "Коллекция пуста, нечего перемешивать."),
                Map.entry("dialog.error.unknown", "Произошла ошибка"),
                Map.entry("dialog.filter.type.title", "Фильтр по типу (меньше чем)"),
                Map.entry("dialog.filter.power.title", "Фильтр по мощности"),
                Map.entry("dialog.filter.power.prompt", "Введите минимальную мощность двигателя:"),
                Map.entry("dialog.filter.power.example", "Например: 100"),
                Map.entry("dialog.group_by.title", "Группировка по полю"),
                Map.entry("dialog.clear.title", "Очистка коллекции"),
                Map.entry("dialog.clear.confirm", "Вы уверены, что хотите удалить ВСЕ свои объекты? Это действие нельзя отменить."),
                Map.entry("dialog.deposit.title", "Пополнение баланса"),
                Map.entry("dialog.deposit.prompt", "Введите сумму пополнения:"),
                Map.entry("dialog.deposit.example", "Например: 1000"),
                Map.entry("dialog.error.positive_amount", "Сумма должна быть больше 0"),
                Map.entry("dialog.error.invalid_amount", "Некорректная сумма"),
                Map.entry("dialog.update.title", "Обновление элемента"),
                Map.entry("dialog.update.prompt", "Введите ID для обновления:"),
                Map.entry("dialog.update.example", "Например: 11"),
                Map.entry("dialog.error.invalid_id", "Некорректный ID"),
                Map.entry("dialog.set_price.title", "Установка цены"),
                Map.entry("dialog.set_price.prompt_id", "Введите ID транспортного средства:"),
                Map.entry("dialog.set_price.prompt_price", "Введите новую цену:"),
                Map.entry("dialog.set_price.example", "Например: 15000"),
                Map.entry("dialog.error.negative_price", "Цена не может быть отрицательной"),
                Map.entry("dialog.error.invalid_price", "Некорректная цена"),
                Map.entry("error.network", "Ошибка сети"),
                Map.entry("error.server", "Ошибка сервера"),
                Map.entry("error.balance_prefix", "Ваш баланс: "),
                Map.entry("error.currency_suffix", " ₽"),
                Map.entry("error.init_connection", "Не удалось инициализировать соединение"),
                Map.entry("error.init_detail", "Ошибка инициализации: "),
                Map.entry("error.connect", "Не удалось подключиться к серверу"),
                Map.entry("error.connect_detail", "Ошибка подключения: "),
                Map.entry("error.handshake", "Сервер не ответил на рукопожатие"),
                Map.entry("error.commands_load", "Ошибка загрузки карты команд"),
                Map.entry("app.status.initializing", "Инициализация подключения..."),
                Map.entry("app.status.connecting", "Подключение к серверу..."),
                Map.entry("app.status.loading_commands", "Загрузка команд..."),
                Map.entry("app.status.ready", "Готово!"),
                Map.entry("app.status.connected", "Подключено"),
                Map.entry("app.commands_loaded", "Загружено команд"),
                Map.entry("app.status.error", "Ошибка"),
                Map.entry("app.status.disconnecting", "Закрытие соединения..."),
                // === АЛИАСЫ ДЛЯ КНОПОК ===
                Map.entry("btn.balance", "Баланс"),
                Map.entry("btn.deposit", "Пополнить"),
                Map.entry("btn.add", "Добавить"),
                Map.entry("btn.remove", "Удалить по ID"),
                Map.entry("btn.shuffle", "Перемешать"),
                Map.entry("btn.buy", "Купить"),
                Map.entry("btn.clear", "Очистить"),
                Map.entry("filter.id", "ID"),
                Map.entry("filter.name", "Имя"),
                Map.entry("filter.owner", "Владелец"),
                Map.entry("filter.min_price", "Цена от"),
                Map.entry("filter.max_price", "Цена до"),
                Map.entry("filter.type", "Тип"),
                Map.entry("filter.fuel", "Топливо")
        ));

        // =====================================================================
        // NORWEGIAN (no_NO)
        // =====================================================================
        resources.put(NO, Map.ofEntries(
                Map.entry("app.title", "Kjøretøybehandler"),
                Map.entry("confirm.exit", "Er du sikker på at du vil avslutte?"),
                Map.entry("auth.login", "Brukernavn"),
                Map.entry("auth.password", "Passord"),
                Map.entry("auth.register", "Registrer"),
                Map.entry("auth.login.button", "Logg inn"),
                Map.entry("auth.register.button", "Registrer deg"),
                Map.entry("auth.login.prompt", "brukernavn"),
                Map.entry("auth.password.prompt", "••••••••"),
                Map.entry("auth.error.empty", "Brukernavn og passord kan ikke være tomme"),
                Map.entry("auth.error.auth", "Ugyldig brukernavn eller passord"),
                Map.entry("auth.error.register", "Registreringsfeil"),
                Map.entry("auth.success.login", "✓ Innlogging vellykket!"),
                Map.entry("main.user.label", "Bruker:"),
                Map.entry("main.table.title", "Objektliste"),
                Map.entry("main.visual.title", "Koordinatvisualisering"),
                Map.entry("main.lang.label", "Språk:"),
                Map.entry("main.btn.balance", "Saldo"),
                Map.entry("main.btn.deposit", "Sett inn"),
                Map.entry("main.btn.add", "Legg til"),
                Map.entry("main.btn.remove", "Fjern etter ID"),
                Map.entry("main.btn.shuffle", "Bland"),
                Map.entry("main.btn.buy", "Kjøp"),
                Map.entry("main.btn.clear", "Tøm"),
                Map.entry("table.filter", "Filtre"),
                Map.entry("table.filter.id", "ID"),
                Map.entry("table.filter.name", "Navn"),
                Map.entry("table.filter.owner", "Eier"),
                Map.entry("table.filter.min_price", "Min. pris"),
                Map.entry("table.filter.max_price", "Maks. pris"),
                Map.entry("table.filter.type", "Type"),
                Map.entry("table.filter.fuel", "Drivstoff"),
                Map.entry("table.warning.select_for_delete", "Velg et element for sletting!"),
                Map.entry("table.warning.select_for_buy", "Velg et element for kjøp!"),
                Map.entry("table.filter.all_types", "Alle typer"),
                Map.entry("table.filter.all_fuels", "Alle drivstoff"),
                Map.entry("col.id", "ID"),
                Map.entry("col.name", "Navn"),
                Map.entry("col.coords", "Koordinater (X,Y)"),
                Map.entry("col.creation_date", "Opprettelsesdato"),
                Map.entry("col.engine_power", "Effekt"),
                Map.entry("col.distance", "Distanse"),
                Map.entry("col.type", "Type"),
                Map.entry("col.fuel", "Drivstoff"),
                Map.entry("col.owner", "Eier"),
                Map.entry("col.price", "Pris"),
                Map.entry("btn.exit", "Logg ut"),
                Map.entry("profile.back", "← Tilbake"),
                Map.entry("profile.about.label", "Om deg:"),
                Map.entry("profile.about.prompt", "Skriv informasjon..."),
                Map.entry("profile.status.online", "Pålogget"),
                Map.entry("dialog.save", "Lagre"),
                Map.entry("dialog.cancel", "Avbryt"),
                Map.entry("dialog.ok", "OK"),
                Map.entry("dialog.confirm", "Bekreft"),
                Map.entry("dialog.add_vehicle", "Legg til kjøretøy"),
                Map.entry("dialog.edit_vehicle", "Rediger kjøretøy"),
                Map.entry("dialog.header.add", "Fyll inn data for nytt kjøretøy"),
                Map.entry("dialog.header.edit", "Endre kjøretøydata"),
                Map.entry("dialog.prompt.name", "Kjøretøyets navn"),
                Map.entry("dialog.prompt.x", "X-koordinat"),
                Map.entry("dialog.prompt.y", "Y-koordinat"),
                Map.entry("dialog.prompt.power", "Motoreffekt"),
                Map.entry("dialog.prompt.distance", "Tilbakelagt distanse"),
                Map.entry("dialog.prompt.price", "Pris"),
                Map.entry("dialog.label.name", "Navn:"),
                Map.entry("dialog.label.coords", "Koordinater (X, Y):"),
                Map.entry("dialog.label.creation_date", "Opprettelsesdato:"),
                Map.entry("dialog.label.power", "Motoreffekt:"),
                Map.entry("dialog.label.distance", "Tilbakelagt distanse:"),
                Map.entry("dialog.label.type", "Type:"),
                Map.entry("dialog.label.fuel", "Drivstoff:"),
                Map.entry("dialog.label.price", "Pris:"),
                Map.entry("dialog.error.invalid_numbers", "Sjekk tallformatet"),
                Map.entry("dialog.error.empty_collection", "Samlingen er tom."),
                Map.entry("dialog.error.unknown", "En feil oppstod"),
                Map.entry("dialog.filter.type.title", "Filtrer etter type (mindre)"),
                Map.entry("dialog.filter.power.title", "Filtrer etter effekt"),
                Map.entry("dialog.filter.power.prompt", "Skriv inn minimum effekt:"),
                Map.entry("dialog.filter.power.example", "F.eks: 100"),
                Map.entry("dialog.group_by.title", "Grupper etter felt"),
                Map.entry("dialog.clear.title", "Tøm samling"),
                Map.entry("dialog.clear.confirm", "Er du sikker? Dette kan ikke angres."),
                Map.entry("dialog.deposit.title", "Sett inn saldo"),
                Map.entry("dialog.deposit.prompt", "Skriv inn beløp:"),
                Map.entry("dialog.deposit.example", "F.eks: 1000"),
                Map.entry("dialog.error.positive_amount", "Beløpet må være > 0"),
                Map.entry("dialog.error.invalid_amount", "Ugyldig beløp"),
                Map.entry("dialog.update.title", "Oppdater element"),
                Map.entry("dialog.update.prompt", "Skriv inn ID:"),
                Map.entry("dialog.update.example", "F.eks: 11"),
                Map.entry("dialog.error.invalid_id", "Ugyldig ID"),
                Map.entry("dialog.set_price.title", "Sett pris"),
                Map.entry("dialog.set_price.prompt_id", "Skriv inn kjøretøy-ID:"),
                Map.entry("dialog.set_price.prompt_price", "Skriv inn ny pris:"),
                Map.entry("dialog.set_price.example", "F.eks: 15000"),
                Map.entry("dialog.error.negative_price", "Pris kan ikke være negativ"),
                Map.entry("dialog.error.invalid_price", "Ugyldig pris"),
                Map.entry("error.network", "Nettverksfeil"),
                Map.entry("error.server", "Serverfeil"),
                Map.entry("error.balance_prefix", "Din saldo: "),
                Map.entry("error.currency_suffix", " kr"),
                Map.entry("error.init_connection", "Kunne ikke initialisere tilkobling"),
                Map.entry("error.init_detail", "Initialiseringsfeil: "),
                Map.entry("error.connect", "Kunne ikke koble til server"),
                Map.entry("error.connect_detail", "Tilkoblingsfeil: "),
                Map.entry("error.handshake", "Server svarte ikke på håndtrykk"),
                Map.entry("error.commands_load", "Feil ved lasting av kommandokart"),
                Map.entry("app.status.initializing", "Initialiserer tilkobling..."),
                Map.entry("app.status.connecting", "Kobler til server..."),
                Map.entry("app.status.loading_commands", "Laster kommandoer..."),
                Map.entry("app.status.ready", "Klar!"),
                Map.entry("app.status.connected", "Tilkoblet"),
                Map.entry("app.commands_loaded", "Kommandoer lastet"),
                Map.entry("app.status.error", "Feil"),
                Map.entry("app.status.disconnecting", "Lukker tilkobling..."),
                // === АЛИАСЫ ДЛЯ КНОПОК ===
                Map.entry("btn.balance", "Saldo"),
                Map.entry("btn.deposit", "Sett inn"),
                Map.entry("btn.add", "Legg til"),
                Map.entry("btn.remove", "Fjern etter ID"),
                Map.entry("btn.shuffle", "Bland"),
                Map.entry("btn.buy", "Kjøp"),
                Map.entry("btn.clear", "Tøm"),
                Map.entry("filter.id", "ID"),
                Map.entry("filter.name", "Navn"),
                Map.entry("filter.owner", "Eier"),
                Map.entry("filter.min_price", "Min. pris"),
                Map.entry("filter.max_price", "Maks. pris"),
                Map.entry("filter.type", "Type"),
                Map.entry("filter.fuel", "Drivstoff")
        ));

        // =====================================================================
        // LITHUANIAN (lt_LT)
        // =====================================================================
        resources.put(LT, Map.ofEntries(
                Map.entry("app.title", "Transporto priemonių valdytojas"),
                Map.entry("confirm.exit", "Ar tikrai norite išeiti?"),
                Map.entry("auth.login", "Prisijungimo vardas"),
                Map.entry("auth.password", "Slaptažodis"),
                Map.entry("auth.register", "Registruotis"),
                Map.entry("auth.login.button", "Prisijungti"),
                Map.entry("auth.register.button", "Registruotis"),
                Map.entry("auth.login.prompt", "prisijungimo vardas"),
                Map.entry("auth.password.prompt", "••••••••"),
                Map.entry("auth.error.empty", "Prisijungimo vardas ir slaptažodis negali būti tušti"),
                Map.entry("auth.error.auth", "Neteisingas prisijungimo vardas arba slaptažodis"),
                Map.entry("auth.error.register", "Registracijos klaida"),
                Map.entry("auth.success.login", "✓ Sėkmingai prisijungta!"),
                Map.entry("main.user.label", "Naudotojas:"),
                Map.entry("main.table.title", "Objektų sąrašas"),
                Map.entry("main.visual.title", "Koordinatų vizualizacija"),
                Map.entry("main.lang.label", "Kalba:"),
                Map.entry("main.btn.balance", "Balansas"),
                Map.entry("main.btn.deposit", "Papildyti"),
                Map.entry("main.btn.add", "Pridėti"),
                Map.entry("main.btn.remove", "Šalinti pagal ID"),
                Map.entry("main.btn.shuffle", "Sumaišyti"),
                Map.entry("main.btn.buy", "Pirkti"),
                Map.entry("main.btn.clear", "Išvalyti"),
                Map.entry("table.filter", "Filtrai"),
                Map.entry("table.filter.id", "ID"),
                Map.entry("table.filter.name", "Vardas"),
                Map.entry("table.filter.owner", "Savininkas"),
                Map.entry("table.filter.min_price", "Min. kaina"),
                Map.entry("table.filter.max_price", "Maks. kaina"),
                Map.entry("table.filter.type", "Tipas"),
                Map.entry("table.filter.fuel", "Kuras"),
                Map.entry("table.warning.select_for_delete", "Pasirinkite elementą šalinimui!"),
                Map.entry("table.warning.select_for_buy", "Pasirinkite elementą pirkimui!"),
                Map.entry("table.filter.all_types", "Visi tipai"),
                Map.entry("table.filter.all_fuels", "Visi kuro tipai"),
                Map.entry("col.id", "ID"),
                Map.entry("col.name", "Pavadinimas"),
                Map.entry("col.coords", "Koordinatės (X,Y)"),
                Map.entry("col.creation_date", "Sukūrimo data"),
                Map.entry("col.engine_power", "Variklio galia"),
                Map.entry("col.distance", "Nuvažiuotas atstumas"),
                Map.entry("col.type", "Tipas"),
                Map.entry("col.fuel", "Kuras"),
                Map.entry("col.owner", "Savininkas"),
                Map.entry("col.price", "Kaina"),
                Map.entry("btn.exit", "Atsijungti"),
                Map.entry("profile.back", "← Grįžti"),
                Map.entry("profile.about.label", "Apie save:"),
                Map.entry("profile.about.prompt", "Įveskite informaciją..."),
                Map.entry("profile.status.online", "Prisijungęs"),
                Map.entry("dialog.save", "Išsaugoti"),
                Map.entry("dialog.cancel", "Atšaukti"),
                Map.entry("dialog.ok", "Gerai"),
                Map.entry("dialog.confirm", "Patvirtinti"),
                Map.entry("dialog.add_vehicle", "Pridėti transporto priemonę"),
                Map.entry("dialog.edit_vehicle", "Redaguoti transporto priemonę"),
                Map.entry("dialog.header.add", "Įveskite naujos transporto priemonės duomenis"),
                Map.entry("dialog.header.edit", "Keisti transporto priemonės duomenis"),
                Map.entry("dialog.prompt.name", "Transporto priemonės pavadinimas"),
                Map.entry("dialog.prompt.x", "X koordinatė"),
                Map.entry("dialog.prompt.y", "Y koordinatė"),
                Map.entry("dialog.prompt.power", "Variklio galia"),
                Map.entry("dialog.prompt.distance", "Nuvažiuotas atstumas"),
                Map.entry("dialog.prompt.price", "Kaina"),
                Map.entry("dialog.label.name", "Pavadinimas:"),
                Map.entry("dialog.label.coords", "Koordinatės (X, Y):"),
                Map.entry("dialog.label.creation_date", "Sukūrimo data:"),
                Map.entry("dialog.label.power", "Variklio galia:"),
                Map.entry("dialog.label.distance", "Nuvažiuotas atstumas:"),
                Map.entry("dialog.label.type", "Tipas:"),
                Map.entry("dialog.label.fuel", "Kuras:"),
                Map.entry("dialog.label.price", "Kaina:"),
                Map.entry("dialog.error.invalid_numbers", "Patikrinkite skaičių formatą"),
                Map.entry("dialog.error.empty_collection", "Kolekcija tuščia."),
                Map.entry("dialog.error.unknown", "Įvyko klaida"),
                Map.entry("dialog.filter.type.title", "Filtruoti pagal tipą (mažiau)"),
                Map.entry("dialog.filter.power.title", "Filtruoti pagal galią"),
                Map.entry("dialog.filter.power.prompt", "Įveskite minimalią galią:"),
                Map.entry("dialog.filter.power.example", "Pvz.: 100"),
                Map.entry("dialog.group_by.title", "Grupuoti pagal lauką"),
                Map.entry("dialog.clear.title", "Išvalyti kolekciją"),
                Map.entry("dialog.clear.confirm", "Ar tikrai? Veiksmas negrįžtamas."),
                Map.entry("dialog.deposit.title", "Papildyti balansą"),
                Map.entry("dialog.deposit.prompt", "Įveskite sumą:"),
                Map.entry("dialog.deposit.example", "Pvz.: 1000"),
                Map.entry("dialog.error.positive_amount", "Suma turi būti > 0"),
                Map.entry("dialog.error.invalid_amount", "Neteisinga suma"),
                Map.entry("dialog.update.title", "Atnaujinti elementą"),
                Map.entry("dialog.update.prompt", "Įveskite ID:"),
                Map.entry("dialog.update.example", "Pvz.: 11"),
                Map.entry("dialog.error.invalid_id", "Neteisingas ID"),
                Map.entry("dialog.set_price.title", "Nustatyti kainą"),
                Map.entry("dialog.set_price.prompt_id", "Įveskite transporto priemonės ID:"),
                Map.entry("dialog.set_price.prompt_price", "Įveskite naują kainą:"),
                Map.entry("dialog.set_price.example", "Pvz.: 15000"),
                Map.entry("dialog.error.negative_price", "Kaina negali būti neigiama"),
                Map.entry("dialog.error.invalid_price", "Neteisinga kaina"),
                Map.entry("error.network", "Tinklo klaida"),
                Map.entry("error.server", "Serverio klaida"),
                Map.entry("error.balance_prefix", "Jūsų balansas: "),
                Map.entry("error.currency_suffix", " €"),
                Map.entry("error.init_connection", "Nepavyko inicializuoti ryšio"),
                Map.entry("error.init_detail", "Inicializavimo klaida: "),
                Map.entry("error.connect", "Nepavyko prisijungti prie serverio"),
                Map.entry("error.connect_detail", "Prisijungimo klaida: "),
                Map.entry("error.handshake", "Serveris neatsakė į rankos paspaudimą"),
                Map.entry("error.commands_load", "Klaida kraunant komandų žemėlapį"),
                Map.entry("app.status.initializing", "Inicijuojamas ryšys..."),
                Map.entry("app.status.connecting", "Jungiamasi prie serverio..."),
                Map.entry("app.status.loading_commands", "Kraunamos komandos..."),
                Map.entry("app.status.ready", "Paruošta!"),
                Map.entry("app.status.connected", "Prisijungta"),
                Map.entry("app.commands_loaded", "Komandos įkeltos"),
                Map.entry("app.status.error", "Klaida"),
                Map.entry("app.status.disconnecting", "Uždaromas ryšys..."),
                // === АЛИАСЫ ДЛЯ КНОПОК ===
                Map.entry("btn.balance", "Balansas"),
                Map.entry("btn.deposit", "Papildyti"),
                Map.entry("btn.add", "Pridėti"),
                Map.entry("btn.remove", "Šalinti pagal ID"),
                Map.entry("btn.shuffle", "Sumaišyti"),
                Map.entry("btn.buy", "Pirkti"),
                Map.entry("btn.clear", "Išvalyti"),
                Map.entry("filter.id", "ID"),
                Map.entry("filter.name", "Vardas"),
                Map.entry("filter.owner", "Savininkas"),
                Map.entry("filter.min_price", "Min. kaina"),
                Map.entry("filter.max_price", "Maks. kaina"),
                Map.entry("filter.type", "Tipas"),
                Map.entry("filter.fuel", "Kuras")
        ));

        // =====================================================================
        // ENGLISH (en_GB)
        // =====================================================================
        resources.put(EN_GB, Map.ofEntries(
                Map.entry("app.title", "Vehicle Manager"),
                Map.entry("confirm.exit", "Are you sure you want to exit?"),
                Map.entry("auth.login", "Username"),
                Map.entry("auth.password", "Password"),
                Map.entry("auth.register", "Register"),
                Map.entry("auth.login.button", "Sign In"),
                Map.entry("auth.register.button", "Register"),
                Map.entry("auth.login.prompt", "username"),
                Map.entry("auth.password.prompt", "••••••••"),
                Map.entry("auth.error.empty", "Username and password cannot be empty"),
                Map.entry("auth.error.auth", "Invalid username or password"),
                Map.entry("auth.error.register", "Registration error"),
                Map.entry("auth.success.login", "✓ Login successful!"),
                Map.entry("main.user.label", "User:"),
                Map.entry("main.table.title", "Objects List"),
                Map.entry("main.visual.title", "Coordinates Visualization"),
                Map.entry("main.lang.label", "Language:"),
                Map.entry("main.btn.balance", "Balance"),
                Map.entry("main.btn.deposit", "Deposit"),
                Map.entry("main.btn.add", "Add"),
                Map.entry("main.btn.remove", "Remove by ID"),
                Map.entry("main.btn.shuffle", "Shuffle"),
                Map.entry("main.btn.buy", "Buy"),
                Map.entry("main.btn.clear", "Clear"),
                Map.entry("table.filter", "Filters"),
                Map.entry("table.filter.id", "ID"),
                Map.entry("table.filter.name", "Name"),
                Map.entry("table.filter.owner", "Owner"),
                Map.entry("table.filter.min_price", "Min Price"),
                Map.entry("table.filter.max_price", "Max Price"),
                Map.entry("table.filter.type", "Type"),
                Map.entry("table.filter.fuel", "Fuel"),
                Map.entry("table.warning.select_for_delete", "Select an item to delete!"),
                Map.entry("table.warning.select_for_buy", "Select an item to buy!"),
                Map.entry("table.filter.all_types", "All Types"),
                Map.entry("table.filter.all_fuels", "All Fuels"),
                Map.entry("col.id", "ID"),
                Map.entry("col.name", "Name"),
                Map.entry("col.coords", "Coords (X,Y)"),
                Map.entry("col.creation_date", "Creation Date"),
                Map.entry("col.engine_power", "Engine Power"),
                Map.entry("col.distance", "Distance Travelled"),
                Map.entry("col.type", "Type"),
                Map.entry("col.fuel", "Fuel"),
                Map.entry("col.owner", "Owner"),
                Map.entry("col.price", "Price"),
                Map.entry("btn.exit", "Sign Out"),
                Map.entry("profile.back", "← Back to Menu"),
                Map.entry("profile.about.label", "About You:"),
                Map.entry("profile.about.prompt", "Enter info about yourself..."),
                Map.entry("profile.status.online", "Online"),
                Map.entry("dialog.save", "Save"),
                Map.entry("dialog.cancel", "Cancel"),
                Map.entry("dialog.ok", "OK"),
                Map.entry("dialog.confirm", "Confirm"),
                Map.entry("dialog.add_vehicle", "Add Vehicle"),
                Map.entry("dialog.edit_vehicle", "Edit Vehicle"),
                Map.entry("dialog.header.add", "Fill in new vehicle data"),
                Map.entry("dialog.header.edit", "Edit vehicle data"),
                Map.entry("dialog.prompt.name", "Vehicle Name"),
                Map.entry("dialog.prompt.x", "Coordinate X"),
                Map.entry("dialog.prompt.y", "Coordinate Y"),
                Map.entry("dialog.prompt.power", "Engine Power"),
                Map.entry("dialog.prompt.distance", "Distance Travelled"),
                Map.entry("dialog.prompt.price", "Price"),
                Map.entry("dialog.label.name", "Name:"),
                Map.entry("dialog.label.coords", "Coordinates (X, Y):"),
                Map.entry("dialog.label.creation_date", "Creation Date:"),
                Map.entry("dialog.label.power", "Engine Power:"),
                Map.entry("dialog.label.distance", "Distance Travelled:"),
                Map.entry("dialog.label.type", "Type:"),
                Map.entry("dialog.label.fuel", "Fuel:"),
                Map.entry("dialog.label.price", "Price:"),
                Map.entry("dialog.error.invalid_numbers", "Check number format"),
                Map.entry("dialog.error.empty_collection", "Collection is empty."),
                Map.entry("dialog.error.unknown", "An error occurred"),
                Map.entry("dialog.filter.type.title", "Filter by Type (Less Than)"),
                Map.entry("dialog.filter.power.title", "Filter by Power"),
                Map.entry("dialog.filter.power.prompt", "Enter minimum engine power:"),
                Map.entry("dialog.filter.power.example", "e.g., 100"),
                Map.entry("dialog.group_by.title", "Group by Field"),
                Map.entry("dialog.clear.title", "Clear Collection"),
                Map.entry("dialog.clear.confirm", "Are you sure? This cannot be undone."),
                Map.entry("dialog.deposit.title", "Deposit Balance"),
                Map.entry("dialog.deposit.prompt", "Enter deposit amount:"),
                Map.entry("dialog.deposit.example", "e.g., 1000"),
                Map.entry("dialog.error.positive_amount", "Amount must be > 0"),
                Map.entry("dialog.error.invalid_amount", "Invalid amount"),
                Map.entry("dialog.update.title", "Update Element"),
                Map.entry("dialog.update.prompt", "Enter ID to update:"),
                Map.entry("dialog.update.example", "e.g., 11"),
                Map.entry("dialog.error.invalid_id", "Invalid ID"),
                Map.entry("dialog.set_price.title", "Set Price"),
                Map.entry("dialog.set_price.prompt_id", "Enter vehicle ID:"),
                Map.entry("dialog.set_price.prompt_price", "Enter new price:"),
                Map.entry("dialog.set_price.example", "e.g., 15000"),
                Map.entry("dialog.error.negative_price", "Price cannot be negative"),
                Map.entry("dialog.error.invalid_price", "Invalid price"),
                Map.entry("error.network", "Network Error"),
                Map.entry("error.server", "Server Error"),
                Map.entry("error.balance_prefix", "Your balance: "),
                Map.entry("error.currency_suffix", " $"),
                Map.entry("error.init_connection", "Failed to initialize connection"),
                Map.entry("error.init_detail", "Initialization error: "),
                Map.entry("error.connect", "Failed to connect to server"),
                Map.entry("error.connect_detail", "Connection error: "),
                Map.entry("error.handshake", "Server did not respond to handshake"),
                Map.entry("error.commands_load", "Error loading command map"),
                Map.entry("app.status.initializing", "Initialising connection..."),
                Map.entry("app.status.connecting", "Connecting to server..."),
                Map.entry("app.status.loading_commands", "Loading commands..."),
                Map.entry("app.status.ready", "Ready!"),
                Map.entry("app.status.connected", "Connected"),
                Map.entry("app.commands_loaded", "Commands loaded"),
                Map.entry("app.status.error", "Error"),
                Map.entry("app.status.disconnecting", "Closing connection..."),
                // === АЛИАСЫ ДЛЯ КНОПОК ===
                Map.entry("btn.balance", "Balance"),
                Map.entry("btn.deposit", "Deposit"),
                Map.entry("btn.add", "Add"),
                Map.entry("btn.remove", "Remove by ID"),
                Map.entry("btn.shuffle", "Shuffle"),
                Map.entry("btn.buy", "Buy"),
                Map.entry("btn.clear", "Clear"),
                Map.entry("filter.id", "ID"),
                Map.entry("filter.name", "Name"),
                Map.entry("filter.owner", "Owner"),
                Map.entry("filter.min_price", "Min Price"),
                Map.entry("filter.max_price", "Max Price"),
                Map.entry("filter.type", "Type"),
                Map.entry("filter.fuel", "Fuel")
        ));
    }

    public String get(String key) {
        return resources.getOrDefault(currentLocale, resources.get(RU)).getOrDefault(key, key);
    }

    public String get(String key, Locale locale) {
        return resources.getOrDefault(locale, resources.get(RU)).getOrDefault(key, key);
    }

    public void setLocale(Locale locale) {
        if (resources.containsKey(locale)) {
            this.currentLocale = locale;
        }
    }

    public Locale getCurrentLocale() {
        return currentLocale;
    }

    public List<Locale> getAvailableLocales() {
        return new ArrayList<>(resources.keySet());
    }

    public String getLocaleDisplayName(Locale locale) {
        return switch (locale.toString()) {
            case "ru_RU" -> "Русский";
            case "no_NO" -> "Norsk";
            case "lt_LT" -> "Lietuvių";
            case "en_GB" -> "English";
            default -> locale.getDisplayName();
        };
    }

    public String formatDateTime(Date date) {
        if (date == null) return "-";
        java.text.SimpleDateFormat sdf = switch (currentLocale.toString()) {
            case "ru_RU" -> new java.text.SimpleDateFormat("dd.MM.yyyy");
            case "no_NO" -> new java.text.SimpleDateFormat("dd.MM.yyyy");
            case "lt_LT" -> new java.text.SimpleDateFormat("yyyy-MM-dd ");
            case "en_GB" -> new java.text.SimpleDateFormat("dd/MM/yyyy ");
            default -> new java.text.SimpleDateFormat("dd.MM.yyyy");
        };
        return sdf.format(date);
    }
}